# Generated by Django 4.2 on 2025-07-08 05:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', ckeditor.fields.RichTextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='capsule_files/')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('unlock_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
